require: rubocop-rspec

AllCops:
  DisplayCopNames: true

  Include:
    - '**/Appraisals'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'lib/generators/enumerate_it/enum/templates/**/*'
    - 'gemfiles/vendor/**/*'

Lint/EndAlignment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/Documentation:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/PredicateName:
  Exclude:
    - 'lib/enumerate_it/class_methods.rb'

Style/GuardClause:
  MinBodyLength: 3

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false
