plugins:
  - rubocop-rspec
  - rubocop-rake

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

  Exclude:
    - 'lib/generators/enumerate_it/enum/templates/**/*'
    - 'gemfiles/vendor/**/*'

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/LineLength:
  Max: 100

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/ElseAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 3

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Naming/PredicatePrefix:
  Exclude:
    - 'lib/enumerate_it/class_methods.rb'

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
